
const colorsDark = {
    primary: '#b5b5ff',
    primaryVariant: '#8B97FF',
    primaryVariantAA: '#8B97FFAA',
    primaryVariant88: '#8B97FF88',
    primaryVariant66: '#8B97FF66',
    primaryVariant55: '#8B97FF55',
    primaryVariant22: '#8B97FF22',
    secondary: '#0C0150',
    secondary88: '#0C015088',
    secondary44: '#0C015044',
    backgroundSecond: '#000',
    buttonSecond: '#6677ff',
    buttonCircleSecond: '#5566fc',
    textVariant: '#fff',
    textVariant8: '#fff8',
    textVariantGray: '#828282',
    backgroundVariant: '#EEE',
    backgroundVariantColor: '#336',
    textGray8: '#ccf8',
    searchFirst: '#8B97FFDD',
    searchSecond: '#8B97FF',
    searchThird: '#8B97FFDD',
    borderVariant: '#1144',
    backgroundCallEnd: '#f66',
    appoimentColor1: "#F88",
    appoimentColor2: "#88F",
    appoimentColor3: "#8F8",
    appoimentColor4: "#FF8",
    stars: "#FFB84E",
    calendarTheme: {
        textSectionTitleColor: '#b6c1cd',
        textSectionTitleDisabledColor: '#d9e1e8',
        selectedDayBackgroundColor: '#00adf5',
        selectedDayTextColor: '#ffffff',
        todayTextColor: '#00adf5',
        dayTextColor: '#8B97FF',
        textDisabledColor: '#8B97FF55',
        dotColor: '#00adf5',
        selectedDotColor: '#ffffff',
        disabledArrowColor: '#d9e1e8',
        monthTextColor: '#fff',
        arrowColor: 'orange',
        indicatorColor: 'blue',
        backgroundColor: 'transparent',
        calendarBackground: 'transparent',
        textDayFontFamily: 'monospace',
        textMonthFontFamily: 'monospace',
        textDayHeaderFontFamily: 'monospace',
        textDayFontWeight: '300',
        textMonthFontWeight: 'bold',
        textDayHeaderFontWeight: '300',
        textDayFontSize: 16,
        textMonthFontSize: 16,
        textDayHeaderFontSize: 16,
    }
};

const colorsLight = {
    primary: '#b5b5ff',
    primaryVariant: '#8B97FF',
    primaryVariantAA: '#8B97FFAA',
    primaryVariant88: '#8B97FF88',
    primaryVariant66: '#8B97FF66',
    primaryVariant55: '#8B97FF55',
    primaryVariant22: '#8B97FF22',
    secondary: '#0C0150',
    secondary88: '#0C015088',
    backgroundSecond: '#000',
    buttonSecond: '#6677ff',
    buttonCircleSecond: '#5566fc',
    textVariant: '#fff',
    textVariant8: '#fff8',
    textVariantGray: '#828282',
    backgroundVariant: '#EEE',
    backgroundVariantColor: '#336',
    textGray8: '#ccf8',
    searchFirst: '#8B97FFDD',
    searchSecond: '#8B97FF',
    searchThird: '#8B97FFDD',
    borderVariant: '#1144',
    backgroundCallEnd: '#f66',
    appoimentColor1: "#F88",
    appoimentColor2: "#88F",
    appoimentColor3: "#8F8",
    appoimentColor4: "#FF8",
    stars: "#FFB84E",
    calendarTheme: {
        textSectionTitleColor: '#b6c1cd',
        textSectionTitleDisabledColor: '#d9e1e8',
        selectedDayBackgroundColor: '#00adf5',
        selectedDayTextColor: '#ffffff',
        todayTextColor: '#00adf5',
        dayTextColor: '#8B97FF',
        textDisabledColor: '#8B97FF55',
        dotColor: '#00adf5',
        selectedDotColor: '#ffffff',
        disabledArrowColor: '#d9e1e8',
        monthTextColor: '#fff',
        arrowColor: 'orange',
        indicatorColor: 'blue',
        backgroundColor: 'transparent',
        calendarBackground: 'transparent',
        textDayFontFamily: 'monospace',
        textMonthFontFamily: 'monospace',
        textDayHeaderFontFamily: 'monospace',
        textDayFontWeight: '300',
        textMonthFontWeight: 'bold',
        textDayHeaderFontWeight: '300',
        textDayFontSize: 16,
        textMonthFontSize: 16,
        textDayHeaderFontSize: 16,
    }
};


export {colorsDark, colorsLight};